import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.*;
import java.awt.*;
import static java.lang.System.out;
import java.text.DecimalFormat;
/**
 *
 * @author zerme
 */
public class Calculos extends javax.swing.JFrame {
    String variantes1[] = {"Con Vbb y Vcc" , "Unicamente con Vcc"};
    String variantes2[] = {"Con Vbb y Vcc" , "Unicamente con Vcc"};
    String variantes3[] = {"Cálculos exactos (utilizando Cto. Equivalente de Thevenin)","Cálculos aproximados (Re ≥ 10R2)" };
    String variantes4[] = {"Con una sola recistencia en Rb","Con dos recistencias en serie en Rb"};
    String variantes5[] = {"Polarización de base común"};
    String ruta="";
    int opcion1, opcion2, circuito;
    int mulRb, mulRc, mulRe, mulR1, mulR2;
    /**
     * Creates new form Calculos
     */
    public Calculos() {
        initComponents();
        this.setSize(1200,850);
        this.setLocationRelativeTo(null);
//        for(String variante : variantes1){
//            variantes.addItem(variante);
//        }
        combo.addItem("------------------Polarización fija------------------");
        combo.addItem("-----Polarización fija con resistencia en emisor-----");
        combo.addItem("---------Polarizacón con divisor de voltaje----------");
        combo.addItem("-----------Polarización con realimentación-----------");
        combo.addItem("--------------Polarización de base común-------------");
    
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Vcc = new java.awt.TextField();
        label1 = new java.awt.Label();
        Rc = new java.awt.TextField();
        label2 = new java.awt.Label();
        Re = new java.awt.TextField();
        label3 = new java.awt.Label();
        Rb = new java.awt.TextField();
        label4 = new java.awt.Label();
        R1 = new java.awt.TextField();
        R2 = new java.awt.TextField();
        label6 = new java.awt.Label();
        Ganancia = new java.awt.TextField();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        Vbb = new java.awt.TextField();
        label5 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        variantes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rbMul = new javax.swing.JComboBox<>();
        r1Mul = new javax.swing.JComboBox<>();
        r2Mul = new javax.swing.JComboBox<>();
        reMul = new javax.swing.JComboBox<>();
        rcMul = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ic = new javax.swing.JLabel();
        ie = new javax.swing.JLabel();
        ibRes = new javax.swing.JLabel();
        vb = new javax.swing.JLabel();
        ve = new javax.swing.JLabel();
        vc = new javax.swing.JLabel();
        vrb = new javax.swing.JLabel();
        vrc = new javax.swing.JLabel();
        vre = new javax.swing.JLabel();
        icRes = new javax.swing.JLabel();
        ieRes = new javax.swing.JLabel();
        veRes = new javax.swing.JLabel();
        vbRes = new javax.swing.JLabel();
        vcRes = new javax.swing.JLabel();
        vreRes = new javax.swing.JLabel();
        vrbRes = new javax.swing.JLabel();
        vrcRes = new javax.swing.JLabel();
        isatRes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ic1 = new javax.swing.JLabel();
        vceRes = new javax.swing.JLabel();
        icqRes = new javax.swing.JLabel();
        vceq = new javax.swing.JLabel();
        icq = new javax.swing.JLabel();
        vceqRes = new javax.swing.JLabel();
        cal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de polarización");

        Vcc.setText("0");

        label1.setText("Vbb");

        Rc.setText("0");

        label2.setText("Vcc");

        Re.setText("0");

        label3.setText("Re");

        Rb.setText("0");

        label4.setText("Rc");

        R1.setText("0");

        R2.setText("0");

        label6.setText("β");

        Ganancia.setText("0");

        label7.setText("R1");

        label8.setText("R2");

        jButton2.setText("Borrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Vbb.setText("0");
        Vbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VbbActionPerformed(evt);
            }
        });

        label5.setText("Rb");

        jLabel2.setText("Variantes");

        variantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variantesActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        rbMul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ω", "KΩ", "MΩ" }));
        rbMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMulActionPerformed(evt);
            }
        });

        r1Mul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ω", "KΩ", "MΩ" }));
        r1Mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1MulActionPerformed(evt);
            }
        });

        r2Mul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ω", "KΩ", "MΩ" }));
        r2Mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2MulActionPerformed(evt);
            }
        });

        reMul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ω", "KΩ", "MΩ" }));
        reMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reMulActionPerformed(evt);
            }
        });

        rcMul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ω", "KΩ", "MΩ"}));
        rcMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcMulActionPerformed(evt);
            }
        });

        jButton1.setText("Atras");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel4.setText("Ib:");

        ic.setText("Ic:");

        ie.setText("Ie:");

        ibRes.setText("0");

        vb.setText("Vb:");

        ve.setText("Ve:");

        vc.setText("Vc:");

        vrb.setText("Vrb:");

        vrc.setText("Vrc:");

        vre.setText("Vre:");

        icRes.setText("0");

        ieRes.setText("0");

        veRes.setText("0");

        vbRes.setText("0");

        vcRes.setText("0");

        vreRes.setText("0");

        vrbRes.setText("0");

        vrcRes.setText("0");

        isatRes.setText("0");

        jLabel5.setText("Vce:");

        ic1.setText("Isat:");

        vceRes.setText("0");

        icqRes.setText("0");

        vceq.setText("Vceq:");

        icq.setText("Icq:");

        vceqRes.setText("0");

        cal.setText("Calcular");
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(variantes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(120, 120, 120))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(5, 5, 5)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(label7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(Ganancia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                    .addComponent(R2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(R1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Rb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Re, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Rc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Vcc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(r1Mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(r2Mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(rbMul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(reMul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(rcMul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(Vbb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ie)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ieRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ic)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(icRes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ve)
                                            .addComponent(vc)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(ibRes, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(19, 19, 19)
                                                        .addComponent(vb))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(ic1)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(isatRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(20, 20, 20)))
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(veRes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(vbRes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(vcRes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(icq)
                                                        .addComponent(vceq))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(vceRes, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(vre)
                                                    .addComponent(vrc)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addComponent(vrb)))
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(vrbRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(vrcRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(vreRes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(icqRes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(vceqRes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(variantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Vbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Vcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rcMul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reMul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbMul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r1Mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2Mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(icRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ic))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ie)
                                            .addComponent(ieRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(vc)
                                            .addComponent(vcRes, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(veRes, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ve))))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vceRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vceq, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1)
                                    .addComponent(cal))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ibRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vb)
                                        .addComponent(vbRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(vrcRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vreRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(vrbRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vrb))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vrc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vre)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vceqRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ic1)
                                .addComponent(isatRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(icq))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(icqRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Vcc.setText("0");
        Vbb.setText("0");
        Rb.setText("0");
        Rc.setText("0");
        Re.setText("0");
        Ganancia.setText("0");
        R1.setText("0");
        R2.setText("0");
        icqRes.setText("0");
        vceRes.setText("0");
        isatRes.setText("0");
        vceqRes.setText("0");
        ibRes.setText("0");
        icRes.setText("0");
        ieRes.setText("0");
        vbRes.setText("0");
        vcRes.setText("0");
        veRes.setText("0");
        vrbRes.setText("0");
        vrcRes.setText("0");
        vreRes.setText("0");
    }//GEN-LAST:event_jButton2MouseClicked

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
        opcion1= combo.getSelectedIndex();
        //System.out.println(opcion1);
        if(opcion1 == 0){
            variantes.removeAllItems();
            for(String variante : variantes1){
               variantes.addItem(variante);
            }
        }
        if(opcion1 == 1){
            variantes.removeAllItems();
            for(String variante : variantes2){
               variantes.addItem(variante);
            }
        }
        if(opcion1 == 2){
            variantes.removeAllItems();
            for(String variante : variantes3){
               variantes.addItem(variante);
            }
        }
        if(opcion1 == 3){
            variantes.removeAllItems();
            for(String variante : variantes4){
               variantes.addItem(variante);
            }
        }
        if(opcion1 == 4){
            variantes.removeAllItems();
            for(String variante : variantes5){
               variantes.addItem(variante);
            }
        }
    }//GEN-LAST:event_comboActionPerformed

    private void variantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variantesActionPerformed
        // TODO add your handling code here:
        opcion2 = variantes.getSelectedIndex();
        Vcc.setEnabled(true);
        Vbb.setEnabled(true);
        Rb.setEnabled(true);
        Rc.setEnabled(true);
        Re.setEnabled(true);
        Ganancia.setEnabled(true);
        R1.setEnabled(true);
        R2.setEnabled(true);
        rbMul.setEnabled(true);
        rcMul.setEnabled(true);
        reMul.setEnabled(true);
        r1Mul.setEnabled(true);
        r2Mul.setEnabled(true);
        if(opcion1 == 0 && opcion2 == 0){
            Re.setEnabled(false);
            R1.setEnabled(false);
            R2.setEnabled(false);
            reMul.setEnabled(false);
            r1Mul.setEnabled(false);
            r2Mul.setEnabled(false);
            this.circuito = 1;
            ruta="/img/polarizacion_fija_2.jpeg";
        }
        if(opcion1 == 0 && opcion2 == 1){
            Re.setEnabled(false);
            Vbb.setEnabled(false);
            R1.setEnabled(false);
            R2.setEnabled(false);
            reMul.setEnabled(false);
            r1Mul.setEnabled(false);
            r2Mul.setEnabled(false);
            this.circuito = 2;
            ruta="/img/polarizacion_fija_1.jpeg";
        }
        if(opcion1 == 1 && opcion2 == 0){
            R1.setEnabled(false);
            R2.setEnabled(false);
            r1Mul.setEnabled(false);
            r2Mul.setEnabled(false);
            this.circuito = 3;
            ruta = "/img/polarizacion_emisor_2.jpeg"; 
        }
        if(opcion1 == 1 && opcion2 == 1){
            Vbb.setEnabled(false);
            R1.setEnabled(false);
            R2.setEnabled(false);
            r1Mul.setEnabled(false);
            r2Mul.setEnabled(false);
            this.circuito = 4;
            ruta = "/img/polarizacion_emisor_1.jpeg";
        }
        if(opcion1 == 2 && opcion2 == 0){
            Vbb.setEnabled(false);
            Rb.setEnabled(false);
            rbMul.setEnabled(false);
            this.circuito = 5;
            ruta = "/img/polarizacion_divisorV_1.jpeg";
        }
        if(opcion1 == 2 && opcion2 == 1){
            Rb.setEnabled(false);
            rbMul.setEnabled(false);
            this.circuito = 6;
            ruta = "/img/polarizacion_divisorV_2.jpeg";
        }
        if(opcion1 == 3 && opcion2 == 0){
            Vbb.setEnabled(false);
            R1.setEnabled(false);
            R2.setEnabled(false);
            r1Mul.setEnabled(false);
            r2Mul.setEnabled(false);
            this.circuito = 7;
            ruta = "/img/polarizacion_retroalimentacion_1.jpeg";
        }
        if(opcion1 == 3 && opcion2 == 1){
            Vbb.setEnabled(false);
            R2.setEnabled(false);
            r2Mul.setEnabled(false);
            this.circuito = 8;
            ruta = "/img/polarizacion_retroalimentacion_2.jpeg";
        }
        if(opcion1 == 4 && opcion2 == 0){
            Vbb.setEnabled(false);
            R1.setEnabled(false);
            R2.setEnabled(false);
            r1Mul.setEnabled(false);
            r2Mul.setEnabled(false);
            this.circuito = 9;
            ruta = "/img/polarizacion_basecomun.jpeg";
        }
        ImageIcon circuito = new ImageIcon(getClass().getResource(ruta));
        ImageIcon tamano = new ImageIcon(circuito.getImage().getScaledInstance(jLabel3.getWidth(),jLabel3.getHeight(),Image.SCALE_DEFAULT));
        jLabel3.setIcon(tamano);
    }//GEN-LAST:event_variantesActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Menu o = new Menu();
        o.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void rcMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcMulActionPerformed
        // TODO add your handling code here:
        mulRc = rcMul.getSelectedIndex();
    }//GEN-LAST:event_rcMulActionPerformed

    private void reMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reMulActionPerformed
        // TODO add your handling code here:
        mulRe= reMul.getSelectedIndex();
    }//GEN-LAST:event_reMulActionPerformed

    private void rbMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMulActionPerformed
        // TODO add your handling code here:
        mulRb= rbMul.getSelectedIndex();
    }//GEN-LAST:event_rbMulActionPerformed

    private void r1MulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1MulActionPerformed
        // TODO add your handling code here:
        mulR1= r1Mul.getSelectedIndex();
    }//GEN-LAST:event_r1MulActionPerformed

    private void r2MulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2MulActionPerformed
        // TODO add your handling code here:
        mulR2= r2Mul.getSelectedIndex();
    }//GEN-LAST:event_r2MulActionPerformed

    private void calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calActionPerformed
        float vcc,vbb,rb,rc,re,ganancia,r1,r2;
        vcc = Float.valueOf(Vcc.getText());
        vbb = Float.valueOf(Vbb.getText());
        rb = Float.valueOf(Rb.getText());
        rc = Float.valueOf(Rc.getText());
        re = Float.valueOf(Re.getText());
        r1 = Float.valueOf(R1.getText());
        r2 = Float.valueOf(R2.getText());
        ganancia = Float.valueOf(Ganancia.getText());
    
        
        
        /*
        out.println(this.mulRc);
        out.println(this.mulRe);
        out.println(this.mulRb);
        out.println(this.mulR1);
        out.println(this.mulR2);
        */
        
        double mc = multi(this.mulRc);
        double me = multi(this.mulRe); 
        double mb = multi(this.mulRb); 
        double mr1 = multi(this.mulR1);
        double mr2 = multi(this.mulR2);
        
        
        
        out.println("Multi");
        out.println(mc);
        out.println(me);
        out.println(mb);
        out.println(mr1);
        out.println(mr2);
     
        /*
        out.println(vcc);
        out.println(vbb);
        out.println(rb);
        out.println(rc);
        out.println(re);
        out.println(r1);
        out.println(r2);
        out.println(ganancia);
        */
           
        switch(circuito){
            case 1:
                out.println("f1");
                polarizacionFija(vcc, vbb, rc, rb, ganancia, mc, mb);
                //fija con 2 voltajes
                break;
            case 2:
                out.println("f2");
                polarizacionFijaUnica(vcc, rc, rb, ganancia, mc, mb);
                //fija con 1 voltajes
                break;
            case 3:
                polarizacionEmisor();
                out.println("f3");
                //re con vcc y vbb
                break;
            case 4:
                polarizacionEmisorUnica(vcc, rc, rb, re, ganancia, mc, mb, me);
                out.println("f4");
                //re vcc
                break;
            case 5:
                divisorVoltajeExacto();
                out.println("f5");
                //divisor de voltaje calculado
                break;
            case 6:
                divisorVoltajeAprox();
                out.println("f6");
                //PROXIMADO
                break;
            case 7:
                retro();
                out.println("f7");
                //retro rb
                break;
            case 8:
                retroSerie();
                out.println("f8");
                //retro serie
                break;
            case 9:
                baseComun();
                out.println("f9");
                //Base comun
                break;
        }
    }//GEN-LAST:event_calActionPerformed

    double multi( int q){
        double p = 0;
        switch (q) {
            case 0:
                p = 1;
                break;
            case 1:
                p = 1000;
                break;
            case 2:
                p = 1000000;
                break;
            default:
                break;
        }
        return p;
    }
    
    void polarizacionFija(float vcc, float vbb, float rc, float rb, float ganancia, double mc, double mb){
        float vce = 0, icsat = 0, ib = 0, ic = 0, vrc = 0, vrb = 0;
        
        this.vbRes.setText(String.valueOf(vbb));
        this.vcRes.setText(String.valueOf(vcc));
        
        
        ib = (float) ((vbb - .7) / (rb * mb));
        this.ibRes.setText(String.valueOf(ib));
        
        ic = ganancia * ib;
        this.icRes.setText(String.valueOf(ic));
        
        vrc = (float) (ic * rc * mc);
        vrb = (float) (ib * mb * rb);
        
        this.vrcRes.setText(String.valueOf(vrc));
        this.vrbRes.setText(String.valueOf(vrb));
        
        vce = vcc - vrc;
        this.vceRes.setText(String.valueOf(vce));
        
        icsat = (float) (vcc / (rc * mc));
        this.isatRes.setText(String.valueOf(icsat));
    }
    
    void polarizacionFijaUnica(float vcc,float rc,float rb,float ganancia, double mc ,double mb ){
        float vce = 0, icsat = 0, ib = 0, ic = 0, vrc = 0, vrb = 0;
        
        this.vbRes.setText(String.valueOf(vcc));
        this.vcRes.setText(String.valueOf(vcc));
        
        ib = (float) ((vcc - .7) / (rb * mb));
        this.ibRes.setText(String.valueOf(ib));
        
        ic = ganancia * ib;
        this.icRes.setText(String.valueOf(ic));
        
        vrc = (float) (ic * rc * mc);
        vrb = (float) (ib * mb * rb);
        
        this.vrcRes.setText(String.valueOf(vrc));
        this.vrbRes.setText(String.valueOf(vrb));
        
        vce = vcc - vrc;
        this.vceRes.setText(String.valueOf(vce));
        
        icsat = (float) (vcc / (rc * mc));
        this.isatRes.setText(String.valueOf(icsat));
        
    }
    
    void polarizacionEmisor(){
        
    }
    
    void polarizacionEmisorUnica( float vcc, float rc, float rb, float re, float ganacia, double mc, double mb,  double me){
        float vce = 0, icsat = 0, ib = 0, ic = 0, vrc = 0, vrb = 0, vre = 0, ie = 0;
        
        rc *= mc;
        rb *= mb;
        re *= me;
        
        this.vbRes.setText(String.valueOf(vcc));
        this.vcRes.setText(String.valueOf(vcc));
        
        //ib = (float) (vcc - .7) / ((rb *(float) mb) + (1 + ganacia)(re* (float me));
        ib = (float) (vcc - .7) / (rb) + (ganacia + 1) * re;
        this.ibRes.setText(String.valueOf(ib));
        
        ic = ganacia * ib;
        this.icRes.setText(String.valueOf(ic));
        
        ie = ic + ib;
        this.icRes.setText(String.valueOf(ie));
        
        vrc = (float) (ic * rc);
        vrb = (float) (ib * rb);
        vre = ib * re;
        
        this.vrcRes.setText(String.valueOf(vrc));
        this.vrbRes.setText(String.valueOf(vrb));
        this.vrbRes.setText(String.valueOf(vre));
        
        vce = vcc - ic * (rc + re);
        this.vceRes.setText(String.valueOf(vce));
        
        icsat = (float) (vcc / (rc + re));
        this.isatRes.setText(String.valueOf(icsat));
  
    }
    
    void divisorVoltajeExacto(){
        
    }
    
    void divisorVoltajeAprox(){
        
    }
    
    void retro(){
       
    }
    
    void retroSerie(){
        
    }
    
    void baseComun(){
        
    }
    
    private void VbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VbbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Ganancia;
    private java.awt.TextField R1;
    private java.awt.TextField R2;
    private java.awt.TextField Rb;
    private java.awt.TextField Rc;
    private java.awt.TextField Re;
    private java.awt.TextField Vbb;
    private java.awt.TextField Vcc;
    private javax.swing.JButton cal;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel ibRes;
    private javax.swing.JLabel ic;
    private javax.swing.JLabel ic1;
    private javax.swing.JLabel icRes;
    private javax.swing.JLabel icq;
    private javax.swing.JLabel icqRes;
    private javax.swing.JLabel ie;
    private javax.swing.JLabel ieRes;
    private javax.swing.JLabel isatRes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JComboBox<String> r1Mul;
    private javax.swing.JComboBox<String> r2Mul;
    private javax.swing.JComboBox<String> rbMul;
    private javax.swing.JComboBox<String> rcMul;
    private javax.swing.JComboBox<String> reMul;
    private javax.swing.JComboBox<String> variantes;
    private javax.swing.JLabel vb;
    private javax.swing.JLabel vbRes;
    private javax.swing.JLabel vc;
    private javax.swing.JLabel vcRes;
    private javax.swing.JLabel vceRes;
    private javax.swing.JLabel vceq;
    private javax.swing.JLabel vceqRes;
    private javax.swing.JLabel ve;
    private javax.swing.JLabel veRes;
    private javax.swing.JLabel vrb;
    private javax.swing.JLabel vrbRes;
    private javax.swing.JLabel vrc;
    private javax.swing.JLabel vrcRes;
    private javax.swing.JLabel vre;
    private javax.swing.JLabel vreRes;
    // End of variables declaration//GEN-END:variables
}
